# Generated by Django 3.2.2 on 2021-05-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coating_no', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thickness', models.IntegerField()),
                ('density', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_od', models.IntegerField()),
                ('pipe_od_unit', models.IntegerField()),
                ('pipe_wt', models.IntegerField()),
                ('pipe_wt_unit', models.IntegerField()),
                ('pipe_density', models.IntegerField()),
                ('pipe_density_unit', models.IntegerField()),
                ('corrosion_allowance', models.IntegerField()),
                ('corrosion_allowance_unit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_empty', models.CharField(blank=True, max_length=500)),
                ('flooded', models.CharField(blank=True, max_length=500)),
                ('hydrotest', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('coating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pipe.coating')),
                ('pipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pipe.pipe')),
            ],
        ),
        migrations.AddField(
            model_name='coating',
            name='pipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pipe.pipe'),
        ),
    ]
