# Generated by Django 3.2.2 on 2021-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='contents',
            name='flooded_content',
            field=models.CharField(blank=True, choices=[('1', 'Air'), ('2', 'Water'), ('3', 'Sea Water')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='contents',
            name='hydrotest_content',
            field=models.CharField(blank=True, choices=[('1', 'Air'), ('2', 'Water'), ('3', 'Sea Water')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='contents',
            name='installation_empty_content',
            field=models.CharField(blank=True, choices=[('1', 'Air'), ('2', 'Water'), ('3', 'Sea Water')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='contents',
            name='flooded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contents',
            name='hydrotest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contents',
            name='installation_empty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='corrosion_allowance_unit',
            field=models.CharField(blank=True, choices=[('1', 'IN'), ('2', 'lb/ft3')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='pipe_density_unit',
            field=models.CharField(blank=True, choices=[('1', 'IN'), ('2', 'lb/ft3')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='pipe_od_unit',
            field=models.CharField(blank=True, choices=[('1', 'IN'), ('2', 'lb/ft3')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='pipe_wt_unit',
            field=models.CharField(blank=True, choices=[('1', 'IN'), ('2', 'lb/ft3')], default=1, max_length=1),
        ),
    ]
